version: "3.1"
services:
  nodeserver:
    build:
      context: ./api
    environment:
      - JWT_SECRET=example
    ports:
      - 8080:8080
    depends_on:
      - mongo
    volumes:
      - ./api:/usr/src/app

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - 8081:80
    depends_on:
      - nodeserver
      - app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  app:
    build:
      context: ./app
    volumes:
      - ./app:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - nodeserver
