version: "3.1"
services:
  nodeserver:
    environment:
      - DOCKER_APP_IMAGE
      - JWT_SECRET=example
      - MONGO_URL
    image: ${DOCKER_APP_IMAGE}
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  nginx:
    environment:
      - DOCKER_NGINX_IMAGE
    restart: always
    image: ${DOCKER_NGINX_IMAGE}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nodeserver
    volumes:
     - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
     - /docker-volumes/etc/letsencrypt/live/mnemosyne-app.fr/fullchain.pem:/etc/letsencrypt/live/mnemosyne-app.fr/fullchain.pem
     - /docker-volumes/etc/letsencrypt/live/mnemosyne-app.fr/privkey.pem:/etc/letsencrypt/live/mnemosyne-app.fr/privkey.pem

