version: "3.1"
services:
    nodeserver:
        build:
            context: ./api
        ports:
            - "8080:8080"
        depends_on:
            - mongo
        volumes: 
          - ./api:/usr/src/app

    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
        depends_on:
          - nodeserver

    mongo:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
      ports:
        - "27017:27017"
