name: Docker build and push to Artifact Registry

on:
  push:
    tags: 
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  GCP_PROJECT_ID: mnemosyne-376320
  GCP_LOCATION: europe-west1
  GCP_REPOSITORY: hello-repo
  PUB_SUB_TOPIC: app_refresh
  NODE_IMAGE: nodeserver
  NGINX_IMAGE: nginx
  CI: false

jobs:
  login-build-push:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Docker node container"
        run: |
          docker build -f prod.Dockerfile \
            --tag "$GCP_LOCATION-docker.pkg.dev/$GCP_PROJECT_ID/$GCP_REPOSITORY/$NODE_IMAGE:$GITHUB_SHA" \
            .
        working-directory: "./api"

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCLOUD_MNEMOSYNE_CREDENTIALS }}"
          token_format: "access_token"

      - name: "Docker login"
        uses: "docker/login-action@v1"
        with:
          registry: "${{ env.GCP_LOCATION }}-docker.pkg.dev"
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"

      - name: "Docker push node image"
        run: |-
          docker push "$GCP_LOCATION-docker.pkg.dev/$GCP_PROJECT_ID/$GCP_REPOSITORY/$NODE_IMAGE:$GITHUB_SHA"

      - run: |-
          docker build -f ./nginx/prod.Dockerfile \
            --tag "$GCP_LOCATION-docker.pkg.dev/$GCP_PROJECT_ID/$GCP_REPOSITORY/$NGINX_IMAGE:$GITHUB_SHA" \
            .

      - name: "Docker push node image"
        run: |-
          docker push "$GCP_LOCATION-docker.pkg.dev/$GCP_PROJECT_ID/$GCP_REPOSITORY/$NGINX_IMAGE:$GITHUB_SHA"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: ">= 363.0.0"

      - name: "Use gcloud CLI"
        run: 'gcloud pubsub topics publish projects/$GCP_PROJECT_ID/topics/$PUB_SUB_TOPIC --message="published new images" --attribute="nodeImage=$GCP_LOCATION-docker.pkg.dev/$GCP_PROJECT_ID/$GCP_REPOSITORY/$NODE_IMAGE:$GITHUB_SHA,nginxImage=$GCP_LOCATION-docker.pkg.dev/$GCP_PROJECT_ID/$GCP_REPOSITORY/$NGINX_IMAGE:$GITHUB_SHA"'
