# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend Test CI

on:
  pull_request:
    branches: ["main"]
    paths: 
      - "app/**"

env:
  CI: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: "./api/package-lock.json"
      - run: npm ci
        working-directory: "./app"
      - run: npm run build --if-present
        working-directory: "./app"
      - run: npm test 
        working-directory: "./app"
